
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minisql;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SQLCODE = 129;
  public static final int DECLARE = 364;
  public static final int INTEGER = 125;
  public static final int CORCHETES = 9;
  public static final int SIZE = 301;
  public static final int DATABASE = 261;
  public static final int RELATIVE = 140;
  public static final int SOME = 51;
  public static final int MONTH = 81;
  public static final int BOTH = 49;
  public static final int GO = 230;
  public static final int PIVOT = 64;
  public static final int CLOSE = 66;
  public static final int STRING = 235;
  public static final int PAD = 24;
  public static final int USE = 304;
  public static final int MODULE = 104;
  public static final int DAY = 23;
  public static final int CONSTRAINT = 311;
  public static final int WRITETEXT = 176;
  public static final int BROWSE = 100;
  public static final int CONTINUE = 151;
  public static final int PROCEDURE = 354;
  public static final int OPENDATASOURCE = 208;
  public static final int WRITE = 82;
  public static final int LEVEL = 59;
  public static final int LLAVE_CERRADA = 6;
  public static final int FETCH = 378;
  public static final int DATETIME2 = 330;
  public static final int ZONE = 54;
  public static final int CATALOG = 117;
  public static final int INTERSECT = 171;
  public static final int SMALLDATETIME = 331;
  public static final int TRUE = 34;
  public static final int DENY = 28;
  public static final int OFF = 25;
  public static final int DEALLOCATE = 177;
  public static final int SECTION = 127;
  public static final int FROM = 224;
  public static final int TEXTSIZE = 137;
  public static final int DUMP = 29;
  public static final int ASIGNAR = 249;
  public static final int SET = 250;
  public static final int ASC = 290;
  public static final int SQLERROR = 158;
  public static final int DIAGNOSTICS = 191;
  public static final int KEY = 306;
  public static final int TIMEZONE_HOUR = 213;
  public static final int SQLCA = 77;
  public static final int RESTRICT = 141;
  public static final int FREETEXT = 153;
  public static final int GET = 27;
  public static final int OPTION = 97;
  public static final int NUMERIC = 340;
  public static final int ARE = 21;
  public static final int LINENO = 94;
  public static final int DESCRIPTOR = 179;
  public static final int PARENTESIS_ABIERTO = 226;
  public static final int CORCHETE_ABIERTO = 2;
  public static final int SECURITYAUDIT = 209;
  public static final int NULLIF = 93;
  public static final int POSITION = 146;
  public static final int DECIMAL = 339;
  public static final int SECOND = 101;
  public static final int COUNT = 275;
  public static final int PRECISION = 166;
  public static final int NONE = 40;
  public static final int LAST = 41;
  public static final int DISCONNECT = 180;
  public static final int CURRENT_USER = 216;
  public static final int EXECUTE = 361;
  public static final int PASSWORD = 350;
  public static final int SAVE = 374;
  public static final int TRUNCATE = 257;
  public static final int DEFAULT = 270;
  public static final int BY = 287;
  public static final int SESSION_USER = 215;
  public static final int DEFERRED = 134;
  public static final int CHAR_LENGHT = 198;
  public static final int EXISTS = 263;
  public static final int PUNTO_COMA = 229;
  public static final int TEXT = 325;
  public static final int BIT = 338;
  public static final int HAVING = 288;
  public static final int LANGUAGE = 144;
  public static final int IDENTITY_INSERT = 206;
  public static final int CURRENT_TIME = 217;
  public static final int OR_OP = 16;
  public static final int INDEX = 260;
  public static final int THEN = 36;
  public static final int BIT_LENGTH = 188;
  public static final int AT = 10;
  public static final int EOF = 0;
  public static final int ALLOCATE = 132;
  public static final int AS = 278;
  public static final int EXTRACT = 106;
  public static final int TRIGGER = 107;
  public static final int OPENROWSET = 183;
  public static final int INT = 246;
  public static final int TIMEZONE_MINUTE = 207;
  public static final int BACKUP = 99;
  public static final int VALUES = 268;
  public static final int ADMIRACION_CERRADO = 4;
  public static final int PORCENTAJE = 266;
  public static final int MENOR_IGUAL = 239;
  public static final int NEXT = 379;
  public static final int ANY = 22;
  public static final int KILL = 55;
  public static final int MAYOR_QUE = 236;
  public static final int SUBSTRING = 175;
  public static final int PUBLIC = 96;
  public static final int SEMANTICSIMILARITYDETAILSTABLE = 201;
  public static final int NOCOUNT = 303;
  public static final int CASCADED = 148;
  public static final int LOGIN = 321;
  public static final int BREAK = 74;
  public static final int PREPARE = 114;
  public static final int END = 363;
  public static final int MODIFY = 343;
  public static final int ELSE = 33;
  public static final int VIEW = 302;
  public static final int PERCENT = 231;
  public static final int AND = 233;
  public static final int DATETIMEOFFSET = 333;
  public static final int NCHAR = 58;
  public static final int RETURN = 368;
  public static final int DBCC = 30;
  public static final int CONTAINS = 150;
  public static final int IGUAL_IGUAL = 241;
  public static final int ROLLBACK = 373;
  public static final int FOREIGN = 307;
  public static final int CONNECTION = 184;
  public static final int ESCAPE = 90;
  public static final int CURSOR = 375;
  public static final int ERROR_STRING = 8;
  public static final int NATURAL = 110;
  public static final int UNPIVOT = 122;
  public static final int BIT_NUM = 245;
  public static final int NONCLUSTERED = 319;
  public static final int RESUME = 347;
  public static final int IMMEDIATE = 174;
  public static final int RULE = 39;
  public static final int INTO = 269;
  public static final int READONLY = 358;
  public static final int ALL = 279;
  public static final int LOAD = 42;
  public static final int TABLESAMPLE = 193;
  public static final int MARK = 371;
  public static final int RECOMPILE = 360;
  public static final int COLUMN = 351;
  public static final int BEGIN = 362;
  public static final int ARROBA = 355;
  public static final int CORRESPONDING = 212;
  public static final int OPENQUERY = 167;
  public static final int OFFSETS = 116;
  public static final int FILENAME = 300;
  public static final int LOWER = 61;
  public static final int SQLWARNING = 190;
  public static final int MULTIPLICACION = 254;
  public static final int OCTET_LENGTH = 219;
  public static final int UNIQUE = 317;
  public static final int GRANT = 78;
  public static final int TRY_CONVERT = 195;
  public static final int ROWS = 38;
  public static final int INTERVAL = 155;
  public static final int OPEN = 380;
  public static final int WORK = 56;
  public static final int CURRENT_DATE = 218;
  public static final int TIMESTAMP = 334;
  public static final int ALTER = 341;
  public static final int PRIVILEGES = 182;
  public static final int TOP = 225;
  public static final int REVOKE = 92;
  public static final int NUMERAL = 7;
  public static final int FULL = 284;
  public static final int RESTORE = 109;
  public static final int EXTERNAL = 136;
  public static final int SUM = 273;
  public static final int MIN = 276;
  public static final int OUT = 356;
  public static final int COMA = 251;
  public static final int TEMPORARY = 163;
  public static final int ABSOLUTE = 133;
  public static final int ORDER = 289;
  public static final int CONVERT = 120;
  public static final int COMPUTE = 121;
  public static final int TO = 11;
  public static final int LIKE = 242;
  public static final int SUMA = 252;
  public static final int FILE = 299;
  public static final int REPLICATION = 313;
  public static final int PRIMARY = 294;
  public static final int VARBINARY = 327;
  public static final int FLOAT = 335;
  public static final int DEFERRABLE = 178;
  public static final int REORGANIZE = 346;
  public static final int DOUBLE = 86;
  public static final int SEMANTICKEYPHRASETABLE = 203;
  public static final int MAYOR_IGUAL = 238;
  public static final int SELECT = 271;
  public static final int NVARCHAR = 222;
  public static final int VARYING = 131;
  public static final int REBUILD = 344;
  public static final int CHECK = 310;
  public static final int FIRST = 73;
  public static final int TRIM = 35;
  public static final int DISABLE = 345;
  public static final int NAMES = 298;
  public static final int INPUT = 75;
  public static final int SQLSTATE = 159;
  public static final int WHERE = 232;
  public static final int UPDATE = 256;
  public static final int BETWEEN = 243;
  public static final int ABORT = 349;
  public static final int IDENTIFICADOR = 248;
  public static final int RAISERROR = 165;
  public static final int MONEY = 336;
  public static final int RECONFIGURE = 196;
  public static final int IDENTITY = 305;
  public static final int GROUP = 286;
  public static final int TRANSLATION = 194;
  public static final int USING = 70;
  public static final int PARENTESIS_CERRADO = 227;
  public static final int CLAUSE = 312;
  public static final int TSEQUAL = 108;
  public static final int PRESERVE = 145;
  public static final int CORCHETE_CERRADO = 3;
  public static final int USER = 293;
  public static final int LLAVE_ABIERTA = 5;
  public static final int DOMAIN = 87;
  public static final int SQL = 26;
  public static final int LOCAL = 60;
  public static final int TRANSLATE = 164;
  public static final int INDENTITYCOL = 199;
  public static final int SYSTEM_USER = 200;
  public static final int VALUE = 84;
  public static final int ONLY = 44;
  public static final int EXIT = 32;
  public static final int PARENTESIS = 17;
  public static final int DIVISION = 255;
  public static final int LEADING = 112;
  public static final int TABLE = 258;
  public static final int SCHEMA = 102;
  public static final int error = 1;
  public static final int REVERT = 91;
  public static final int WAITFOR = 130;
  public static final int FORTRAN = 124;
  public static final int STATISTICS = 189;
  public static final int MENOR_QUE = 237;
  public static final int NOCHECK = 111;
  public static final int TIME = 332;
  public static final int LEFT = 282;
  public static final int OR = 234;
  public static final int PROC = 353;
  public static final int ASSERTION = 161;
  public static final int WHENEVER = 160;
  public static final int ON = 264;
  public static final int CASCADE = 118;
  public static final int EXCEPTION = 162;
  public static final int CHAR = 323;
  public static final int OF = 13;
  public static final int ROWGUIDCOL = 181;
  public static final int DELETE = 223;
  public static final int UPPER = 68;
  public static final int ADD = 352;
  public static final int ADA = 20;
  public static final int COMMIT = 372;
  public static final int CLUSTERED = 318;
  public static final int INT_NUM = 244;
  public static final int ACTION = 85;
  public static final int JOIN = 280;
  public static final int WHEN = 57;
  public static final int NULL = 265;
  public static final int MINUTE = 105;
  public static final int INNER = 281;
  public static final int DISTRIBUTED = 192;
  public static final int TRAILING = 138;
  public static final int CONTAINSTABLE = 211;
  public static final int TRANSACTION = 370;
  public static final int NO = 12;
  public static final int OPENXML = 115;
  public static final int FUNCTION = 366;
  public static final int PRIOR = 63;
  public static final int SPACE = 76;
  public static final int CAST = 47;
  public static final int CHAR_LENGTH = 220;
  public static final int SHUTDOWN = 156;
  public static final int INSENSITIVE = 376;
  public static final int NAME = 297;
  public static final int PUNTO = 228;
  public static final int SCROLL = 377;
  public static final int CASE = 46;
  public static final int ERRLVL = 89;
  public static final int PLAN = 43;
  public static final int UPDATETEXT = 186;
  public static final int UNION = 67;
  public static final int DROP = 259;
  public static final int MAX = 277;
  public static final int OUTPUT = 357;
  public static final int PRINT = 62;
  public static final int INDICATOR = 170;
  public static final int FILLFACTOR = 187;
  public static final int IMAGE = 326;
  public static final int GLOBAL = 103;
  public static final int PARTIAL = 113;
  public static final int COLLATION = 168;
  public static final int INCLUDE = 320;
  public static final int GOTO = 53;
  public static final int WHILE = 83;
  public static final int DATETIME = 329;
  public static final int SEMANTICSIMILARITYTABLE = 202;
  public static final int CONNECT = 119;
  public static final int VARCHAR = 324;
  public static final int CURRENT_TIMESTAMP = 204;
  public static final int BULK = 50;
  public static final int INITIALLY = 172;
  public static final int FALSE = 71;
  public static final int SESSION = 128;
  public static final int RESTA = 253;
  public static final int AUTHORIZATION = 214;
  public static final int EXEC = 365;
  public static final int REFERENCES = 308;
  public static final int CREATE = 292;
  public static final int AND_OP = 15;
  public static final int REAL = 337;
  public static final int INSERT = 267;
  public static final int CHECKPOINT = 185;
  public static final int PAUSE = 348;
  public static final int FLOAT_NUM = 247;
  public static final int ISOLATION = 173;
  public static final int READ = 37;
  public static final int SMALLINT = 157;
  public static final int CURRENT = 342;
  public static final int WITH = 296;
  public static final int CHARACTER = 169;
  public static final int DATE = 328;
  public static final int TRAN = 369;
  public static final int DISK = 31;
  public static final int DESCRIBE = 135;
  public static final int ENCRYPTION = 359;
  public static final int HOLDLOCK = 154;
  public static final int OVER = 45;
  public static final int OUTER = 285;
  public static final int DESC = 291;
  public static final int DEC = 315;
  public static final int USAGE = 69;
  public static final int HOUR = 48;
  public static final int FREETEXTTABLE = 210;
  public static final int LLAVES = 18;
  public static final int IS = 314;
  public static final int RETURNS = 367;
  public static final int ROWCOUNT = 142;
  public static final int IN = 316;
  public static final int OVERLAPS = 147;
  public static final int SETUSER = 126;
  public static final int NUMERALES = 19;
  public static final int MERGE = 80;
  public static final int DISTINCT = 272;
  public static final int IF = 262;
  public static final int DIFERENTE_DE = 240;
  public static final int CONSTRAINTS = 197;
  public static final int ERROR_COMENTARIO = 14;
  public static final int UNKNOWN = 123;
  public static final int RIGHT = 283;
  public static final int NOT = 309;
  public static final int CROSS = 65;
  public static final int MATCH = 79;
  public static final int YEAR = 52;
  public static final int PASCAL = 95;
  public static final int USABLE = 98;
  public static final int IDENTITYCOL = 221;
  public static final int EXCEPT = 88;
  public static final int NATIONAL = 143;
  public static final int READTEXT = 139;
  public static final int COLLATE = 295;
  public static final int CHARACTER_LENGTH = 205;
  public static final int FOUND = 72;
  public static final int AVG = 274;
  public static final int UNUSABLE = 152;
  public static final int FOR = 322;
  public static final int COALESCE = 149;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "ADMIRACION_CERRADO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "NUMERAL",
  "ERROR_STRING",
  "CORCHETES",
  "AT",
  "TO",
  "NO",
  "OF",
  "ERROR_COMENTARIO",
  "AND_OP",
  "OR_OP",
  "PARENTESIS",
  "LLAVES",
  "NUMERALES",
  "ADA",
  "ARE",
  "ANY",
  "DAY",
  "PAD",
  "OFF",
  "SQL",
  "GET",
  "DENY",
  "DUMP",
  "DBCC",
  "DISK",
  "EXIT",
  "ELSE",
  "TRUE",
  "TRIM",
  "THEN",
  "READ",
  "ROWS",
  "RULE",
  "NONE",
  "LAST",
  "LOAD",
  "PLAN",
  "ONLY",
  "OVER",
  "CASE",
  "CAST",
  "HOUR",
  "BOTH",
  "BULK",
  "SOME",
  "YEAR",
  "GOTO",
  "ZONE",
  "KILL",
  "WORK",
  "WHEN",
  "NCHAR",
  "LEVEL",
  "LOCAL",
  "LOWER",
  "PRINT",
  "PRIOR",
  "PIVOT",
  "CROSS",
  "CLOSE",
  "UNION",
  "UPPER",
  "USAGE",
  "USING",
  "FALSE",
  "FOUND",
  "FIRST",
  "BREAK",
  "INPUT",
  "SPACE",
  "SQLCA",
  "GRANT",
  "MATCH",
  "MERGE",
  "MONTH",
  "WRITE",
  "WHILE",
  "VALUE",
  "ACTION",
  "DOUBLE",
  "DOMAIN",
  "EXCEPT",
  "ERRLVL",
  "ESCAPE",
  "REVERT",
  "REVOKE",
  "NULLIF",
  "LINENO",
  "PASCAL",
  "PUBLIC",
  "OPTION",
  "USABLE",
  "BACKUP",
  "BROWSE",
  "SECOND",
  "SCHEMA",
  "GLOBAL",
  "MODULE",
  "MINUTE",
  "EXTRACT",
  "TRIGGER",
  "TSEQUAL",
  "RESTORE",
  "NATURAL",
  "NOCHECK",
  "LEADING",
  "PARTIAL",
  "PREPARE",
  "OPENXML",
  "OFFSETS",
  "CATALOG",
  "CASCADE",
  "CONNECT",
  "CONVERT",
  "COMPUTE",
  "UNPIVOT",
  "UNKNOWN",
  "FORTRAN",
  "INTEGER",
  "SETUSER",
  "SECTION",
  "SESSION",
  "SQLCODE",
  "WAITFOR",
  "VARYING",
  "ALLOCATE",
  "ABSOLUTE",
  "DEFERRED",
  "DESCRIBE",
  "EXTERNAL",
  "TEXTSIZE",
  "TRAILING",
  "READTEXT",
  "RELATIVE",
  "RESTRICT",
  "ROWCOUNT",
  "NATIONAL",
  "LANGUAGE",
  "PRESERVE",
  "POSITION",
  "OVERLAPS",
  "CASCADED",
  "COALESCE",
  "CONTAINS",
  "CONTINUE",
  "UNUSABLE",
  "FREETEXT",
  "HOLDLOCK",
  "INTERVAL",
  "SHUTDOWN",
  "SMALLINT",
  "SQLERROR",
  "SQLSTATE",
  "WHENEVER",
  "ASSERTION",
  "EXCEPTION",
  "TEMPORARY",
  "TRANSLATE",
  "RAISERROR",
  "PRECISION",
  "OPENQUERY",
  "COLLATION",
  "CHARACTER",
  "INDICATOR",
  "INTERSECT",
  "INITIALLY",
  "ISOLATION",
  "IMMEDIATE",
  "SUBSTRING",
  "WRITETEXT",
  "DEALLOCATE",
  "DEFERRABLE",
  "DESCRIPTOR",
  "DISCONNECT",
  "ROWGUIDCOL",
  "PRIVILEGES",
  "OPENROWSET",
  "CONNECTION",
  "CHECKPOINT",
  "UPDATETEXT",
  "FILLFACTOR",
  "BIT_LENGTH",
  "STATISTICS",
  "SQLWARNING",
  "DIAGNOSTICS",
  "DISTRIBUTED",
  "TABLESAMPLE",
  "TRANSLATION",
  "TRY_CONVERT",
  "RECONFIGURE",
  "CONSTRAINTS",
  "CHAR_LENGHT",
  "INDENTITYCOL",
  "SYSTEM_USER",
  "SEMANTICSIMILARITYDETAILSTABLE",
  "SEMANTICSIMILARITYTABLE",
  "SEMANTICKEYPHRASETABLE",
  "CURRENT_TIMESTAMP",
  "CHARACTER_LENGTH",
  "IDENTITY_INSERT",
  "TIMEZONE_MINUTE",
  "OPENDATASOURCE",
  "SECURITYAUDIT",
  "FREETEXTTABLE",
  "CONTAINSTABLE",
  "CORRESPONDING",
  "TIMEZONE_HOUR",
  "AUTHORIZATION",
  "SESSION_USER",
  "CURRENT_USER",
  "CURRENT_TIME",
  "CURRENT_DATE",
  "OCTET_LENGTH",
  "CHAR_LENGTH",
  "IDENTITYCOL",
  "NVARCHAR",
  "DELETE",
  "FROM",
  "TOP",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "PUNTO",
  "PUNTO_COMA",
  "GO",
  "PERCENT",
  "WHERE",
  "AND",
  "OR",
  "STRING",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "DIFERENTE_DE",
  "IGUAL_IGUAL",
  "LIKE",
  "BETWEEN",
  "INT_NUM",
  "BIT_NUM",
  "INT",
  "FLOAT_NUM",
  "IDENTIFICADOR",
  "ASIGNAR",
  "SET",
  "COMA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "UPDATE",
  "TRUNCATE",
  "TABLE",
  "DROP",
  "INDEX",
  "DATABASE",
  "IF",
  "EXISTS",
  "ON",
  "NULL",
  "PORCENTAJE",
  "INSERT",
  "VALUES",
  "INTO",
  "DEFAULT",
  "SELECT",
  "DISTINCT",
  "SUM",
  "AVG",
  "COUNT",
  "MIN",
  "MAX",
  "AS",
  "ALL",
  "JOIN",
  "INNER",
  "LEFT",
  "RIGHT",
  "FULL",
  "OUTER",
  "GROUP",
  "BY",
  "HAVING",
  "ORDER",
  "ASC",
  "DESC",
  "CREATE",
  "USER",
  "PRIMARY",
  "COLLATE",
  "WITH",
  "NAME",
  "NAMES",
  "FILE",
  "FILENAME",
  "SIZE",
  "VIEW",
  "NOCOUNT",
  "USE",
  "IDENTITY",
  "KEY",
  "FOREIGN",
  "REFERENCES",
  "NOT",
  "CHECK",
  "CONSTRAINT",
  "CLAUSE",
  "REPLICATION",
  "IS",
  "DEC",
  "IN",
  "UNIQUE",
  "CLUSTERED",
  "NONCLUSTERED",
  "INCLUDE",
  "LOGIN",
  "FOR",
  "CHAR",
  "VARCHAR",
  "TEXT",
  "IMAGE",
  "VARBINARY",
  "DATE",
  "DATETIME",
  "DATETIME2",
  "SMALLDATETIME",
  "TIME",
  "DATETIMEOFFSET",
  "TIMESTAMP",
  "FLOAT",
  "MONEY",
  "REAL",
  "BIT",
  "DECIMAL",
  "NUMERIC",
  "ALTER",
  "CURRENT",
  "MODIFY",
  "REBUILD",
  "DISABLE",
  "REORGANIZE",
  "RESUME",
  "PAUSE",
  "ABORT",
  "PASSWORD",
  "COLUMN",
  "ADD",
  "PROC",
  "PROCEDURE",
  "ARROBA",
  "OUT",
  "OUTPUT",
  "READONLY",
  "ENCRYPTION",
  "RECOMPILE",
  "EXECUTE",
  "BEGIN",
  "END",
  "DECLARE",
  "EXEC",
  "FUNCTION",
  "RETURNS",
  "RETURN",
  "TRAN",
  "TRANSACTION",
  "MARK",
  "COMMIT",
  "ROLLBACK",
  "SAVE",
  "CURSOR",
  "INSENSITIVE",
  "SCROLL",
  "FETCH",
  "NEXT",
  "OPEN"
  };
}

