/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minisql;

/**
 *
 * @author fabia
 */
public enum Tokens {
    RESERVADAS,ERROR,IDENTIFICADOR,Comentario_LineaUnica,INT,BIT,FLOAT,
    SUMA,RESTA,MULTIPLICACION,DIVISION,PORCENTAJE,MENOR_QUE,MENOR_IGUAL,MAYOR_QUE,
    MAYOR_IGUAL,ASIGNAR,IGUAL_IGUAL,DIFERENTE_DE,AND,OR,ADMIRACION_CERRADO,PUNTO_COMA,
    COMA,PUNTO,CORCHETE_ABIERTO,CORCHETE_CERRADO,PARENTESIS_ABIERTO,PARENTESIS_CERRADO,
    LLAVE_ABIERTA,LLAVE_CERRADA,CORCHETES,PARENTESIS,LLAVES,ARROBA,NUMERAL,NUMERALES,STRING,
    COMENTARIO_MULTILINEA,ERROR_STRING,ERROR_COMENTARIO,ERROR_FLOAT
}
