
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minisql;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int WHERE = 11;
  public static final int FROM = 3;
  public static final int AND = 12;
  public static final int PUNTO = 7;
  public static final int PARENTESIS_ABIERTO = 5;
  public static final int PERCENT = 10;
  public static final int INT = 25;
  public static final int OR = 13;
  public static final int MENOR_IGUAL = 18;
  public static final int BETWEEN = 22;
  public static final int DIFERENTE_DE = 19;
  public static final int MAYOR_IGUAL = 17;
  public static final int MAYOR_QUE = 15;
  public static final int NUM = 23;
  public static final int GO = 9;
  public static final int PARENTESIS_CERRADO = 6;
  public static final int STRING = 14;
  public static final int MENOR_QUE = 16;
  public static final int FLOAT = 26;
  public static final int IGUAL_IGUAL = 20;
  public static final int BIT = 24;
  public static final int EOF = 0;
  public static final int TOP = 4;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 27;
  public static final int LIKE = 21;
  public static final int PUNTO_COMA = 8;
  public static final int DELETE = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DELETE",
  "FROM",
  "TOP",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "PUNTO",
  "PUNTO_COMA",
  "GO",
  "PERCENT",
  "WHERE",
  "AND",
  "OR",
  "STRING",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "DIFERENTE_DE",
  "IGUAL_IGUAL",
  "LIKE",
  "BETWEEN",
  "NUM",
  "BIT",
  "INT",
  "FLOAT",
  "IDENTIFICADOR"
  };
}

